### ISSUE TITLE
Click in time slider restarts the video or does nothing.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/videos#15]
### Steps to reproduce

1. Upload a video.
2. Reproduce it.
3. Try to jump to the middle of the video, clicking in the time slider.

### Expected behaviour
Video continues from the middle 

### Actual behaviour
Video is restarted (Chrome) or nothing happens (Firefox).

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
```

### Client configuration

**browser**
Chrome 41, Firefox

**Comment by LukasReschke** [comment]
You probably want to file this at https://github.com/owncloud/apps for `files_videoviewer`. This app is kinda dead and not the one we ship.

**Comment by SergioBertolinSG** [comment]
Ok Lukas, thanks.
