### ISSUE TITLE
Issues Streaming Video Owncloud 8.1

### ISSUE THREAD

**Issue by jcmorales85** [owncloud/videos#19]
### Steps to reproduce
1. Login to owncloud
2. Locate video (.MP4 recorded by Samsung Galaxy S5)
3. Attempt to play video
### Expected behaviour
- It should stream the video.
### Actual behaviour
- Video just loads continuously (videos 25 MB to 250 MB have been tried)
### Server configuration

**Operating system**:
Ubuntu 14.04.3

**Web server:**
- Apache 2.4.7

**Database:**
- Mysql version 14.14 distrib 5.5.44

**PHP version:**
- PHP 5.5.9

**ownCloud version:** (see ownCloud admin page)
- 8.1.3 (stable)

**Updated from an older ownCloud or fresh install:**
- Fresh install

**List of activated apps:**
- Default apps enabled, haven't changed anything here

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

- OC\HintException: [O]: Missing memcache class \OC\Memcache\APCu for local cache (Is the matching PHP module installed and enabled ?)

**The content of config/config.php:**

- OC\HintException: [O]: Missing memcache class \OC\Memcache\APCu for local cache (Is the matching PHP module installed and enabled ?)

**Are you using external storage, if yes which one:** local/smb/sftp/...
- No

**Are you using encryption:** yes/no
- No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
-No 

### Client configuration
- Chrome, IE

**Operating system:**
- Windows 10, Windows 7
```

**Comment by DeepDiver1975** [comment]
> ownCloud version: (see ownCloud admin page)
> 
> ```
> 8.1.3 (stable)
> ```

the videos app is only working up to 7.0 - sure we are talking about the same thing?

**Comment by jcmorales85** [comment]
@DeepDiver1975  Thank you, that's a start!  Since reading your response, I've gone ahead and installed https://apps.owncloud.com/content/show.php/VideoJS+Sublime?content=173993.

I've also gone ahead and installed the X-Sendfile module listed below.
https://doc.owncloud.org/server/7.0/admin_manual/configuration/serving_static_files_configuration.html

My only issue at the moment is that I have no idea where I'm supposed to add the coding under configuration.

<Directory /var/www/owncloud>
    ...
    SetEnv MOD_X_SENDFILE_ENABLED 1
    XSendFile On
    XSendFileAllowAbove On
</Directory>

**Comment by jcmorales85** [comment]
@DeepDiver1975 Thank you, thank you, thank you!!!!

I never thought to look into the app itself.  Since your reply, I have since then disabled the default app and installed VideoJS (found below).

https://apps.owncloud.com/content/show.php/VideoJS+Sublime?content=173993

After enabling the X-Sendile mod and editing the configuration file (found below), I now have video playback!!!!  Thank you again good sir.

https://doc.owncloud.org/server/6.0/admin_manual/configuration/xsendfile.html
